# Useful commands:
# docker-compose build
# docker-compose up
# docker-compose ps
# docker compose stop
# docker-compose down

version: '3.7'

services:
  app:
    build:
      context: ""
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

#  postgres:
#    image: "postgres:10"